name = "kore-website"
compatibility_date = "2026-06-28"

[assets]
directory = "./website/.kobweb/site"
not_found_handling = "404-page"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
