package io.github.ayfri.kore.ksp

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.Modifier
import java.io.OutputStreamWriter

private const val ANNOTATION_NAME = "io.github.ayfri.kore.serializers.GeneratedSealedSerializer"

class SealedSerializerProcessor(
	private val codeGenerator: CodeGenerator,
	private val logger: KSPLogger,
) : SymbolProcessor {
	private var processed = false

	override fun process(resolver: Resolver): List<KSAnnotated> {
		// Everything is emitted in the first round, so later rounds would only rescan the files we just generated.
		if (processed) return emptyList()
		processed = true

		val symbols = resolver.getSymbolsWithAnnotation(ANNOTATION_NAME)

		for (symbol in symbols) {
			if (symbol !is KSClassDeclaration || Modifier.SEALED !in symbol.modifiers) {
				logger.error("@GeneratedSealedSerializer can only be applied to a sealed class/interface.", symbol)
				continue
			}

			generateFactory(symbol)
		}

		return emptyList()
	}

	// Recurses through nested sealed subclasses down to concrete leaves, deduplicating by qualified name so a leaf
	// reachable through more than one intermediate sealed type (e.g. a diamond hierarchy) is only emitted once.
	private fun leavesOf(declaration: KSClassDeclaration): List<KSClassDeclaration> {
		val direct = declaration.getSealedSubclasses().toList()
		return if (direct.isEmpty()) listOf(declaration) else direct.flatMap(::leavesOf)
	}

	private fun generateFactory(declaration: KSClassDeclaration) {
		val subclasses = declaration.getSealedSubclasses().toList()
			.flatMap(::leavesOf)
			.distinctBy { it.qualifiedName?.asString() }
		if (subclasses.isEmpty()) {
			logger.error("Sealed family '${declaration.simpleName.asString()}' has no subclasses.", declaration)
			return
		}

		val sortedSubclasses = subclasses.sortedBy { it.simpleName.asString() }
		val simpleName = declaration.simpleName.asString()
		val packageName = declaration.packageName.asString()
		val functionName = simpleName.replaceFirstChar { it.lowercase() } + "SealedSerializer"

		fun referenceName(classDeclaration: KSClassDeclaration): String {
			val fqName = classDeclaration.qualifiedName!!.asString()
			val classPackage = classDeclaration.packageName.asString()
			return if (classPackage == packageName) fqName.removePrefix("$classPackage.") else fqName
		}

		val baseFqName = referenceName(declaration)
		val subclassFqNames = sortedSubclasses.map { referenceName(it) }
		val dispatcher = "io.github.ayfri.kore.serializers.SealedDispatcher<$baseFqName>"
		val serializer = "kotlinx.serialization.KSerializer"

		val source = buildString {
			appendLine("// GENERATED by kore-ksp. Do not edit.")
			if (packageName.isNotEmpty()) {
				appendLine("package $packageName")
				appendLine()
			}
			// Switching on the simple name loads only the matched subtype, where an `is` chain loads every class it tests
			// (58 advancement triggers: 65ms cold down to 4ms). Homonyms and minified names fall back to the chain.
			appendLine("@Suppress(\"UNCHECKED_CAST\")")
			appendLine("internal fun $functionName(): $dispatcher = object : $dispatcher(\"$simpleName\") {")
			appendLine("\toverride fun serializerOf(value: $baseFqName) = when (io.github.ayfri.kore.serializers.subtypeName(value)) {")
			sortedSubclasses.groupBy { it.simpleName.asString() }.forEach { (name, homonyms) ->
				homonyms.singleOrNull()?.let { appendLine("\t\t\"$name\" -> ${referenceName(it)}.serializer()") }
			}
			appendLine("\t\telse -> when (value) {")
			subclassFqNames.forEach { appendLine("\t\t\tis $it -> $it.serializer()") }
			appendLine("\t\t}")
			appendLine("\t} as $serializer<$baseFqName>")
			appendLine()
			appendLine("\toverride fun serializers(): List<$serializer<out $baseFqName>> = listOf(")
			subclassFqNames.forEach { appendLine("\t\t$it.serializer(),") }
			appendLine("\t)")
			appendLine("}")
		}

		val dependencySources =
			(listOfNotNull(declaration.containingFile) + sortedSubclasses.mapNotNull { it.containingFile })
				.distinct()
				.toTypedArray()

		val file = codeGenerator.createNewFile(
			Dependencies(false, *dependencySources),
			packageName,
			"${simpleName}SealedSerializer",
			"kt",
		)

		OutputStreamWriter(file).use { it.write(source) }
	}
}
