package io.github.ayfri.kore.ksp

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.Modifier
import java.io.OutputStreamWriter

private const val ANNOTATION_NAME = "io.github.ayfri.kore.serializers.GeneratedSealedSerializer"

class SealedSerializerProcessor(
	private val codeGenerator: CodeGenerator,
	private val logger: KSPLogger,
) : SymbolProcessor {
	override fun process(resolver: Resolver): List<KSAnnotated> {
		val symbols = resolver.getSymbolsWithAnnotation(ANNOTATION_NAME)

		for (symbol in symbols) {
			if (symbol !is KSClassDeclaration || Modifier.SEALED !in symbol.modifiers) {
				logger.error("@GeneratedSealedSerializer can only be applied to a sealed class/interface.", symbol)
				continue
			}

			generateFactory(symbol)
		}

		return emptyList()
	}

	private fun generateFactory(declaration: KSClassDeclaration) {
		val subclasses = declaration.getSealedSubclasses().toList()
		if (subclasses.isEmpty()) {
			logger.error("Sealed family '${declaration.simpleName.asString()}' has no subclasses.", declaration)
			return
		}

		val sortedSubclasses = subclasses.sortedBy { it.simpleName.asString() }
		val simpleName = declaration.simpleName.asString()
		val packageName = declaration.packageName.asString()
		val functionName = simpleName.replaceFirstChar { it.lowercase() } + "SealedSerializer"

		fun referenceName(classDeclaration: KSClassDeclaration): String {
			val fqName = classDeclaration.qualifiedName!!.asString()
			val classPackage = classDeclaration.packageName.asString()
			return if (classPackage == packageName) fqName.removePrefix("$classPackage.") else fqName
		}

		val baseFqName = referenceName(declaration)
		val subclassFqNames = sortedSubclasses.map { referenceName(it) }

		val source = buildString {
			appendLine("// GENERATED by kore-ksp. Do not edit.")
			if (packageName.isNotEmpty()) {
				appendLine("package $packageName")
				appendLine()
			}
			appendLine("@OptIn(kotlinx.serialization.InternalSerializationApi::class)")
			appendLine("internal fun $functionName(): kotlinx.serialization.SealedClassSerializer<$baseFqName> {")
			appendLine("\treturn kotlinx.serialization.SealedClassSerializer(")
			appendLine("\t\t\"$simpleName\",")
			appendLine("\t\t$baseFqName::class,")
			appendLine("\t\tarrayOf(")
			subclassFqNames.forEach { appendLine("\t\t\t$it::class,") }
			appendLine("\t\t),")
			appendLine("\t\tarrayOf(")
			subclassFqNames.forEach { appendLine("\t\t\t$it.serializer(),") }
			appendLine("\t\t),")
			appendLine("\t)")
			appendLine("}")
		}

		val dependencySources =
			(listOfNotNull(declaration.containingFile) + sortedSubclasses.mapNotNull { it.containingFile })
				.distinct()
				.toTypedArray()

		val file = codeGenerator.createNewFile(
			Dependencies(false, *dependencySources),
			packageName,
			"${simpleName}SealedSerializer",
			"kt",
		)

		OutputStreamWriter(file).use { it.write(source) }
	}
}
