package io.github.ayfri.kore.ksp

import com.google.devtools.ksp.getAllSuperTypes
import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import java.io.OutputStreamWriter

private const val ANNOTATION_NAME = "io.github.ayfri.kore.serializers.GeneratedSerializerMap"

class SerializerMapProcessor(
	private val codeGenerator: CodeGenerator,
	private val logger: KSPLogger,
) : SymbolProcessor {
	override fun process(resolver: Resolver): List<KSAnnotated> {
		val symbols = resolver.getSymbolsWithAnnotation(ANNOTATION_NAME)

		for (symbol in symbols) {
			if (symbol !is KSClassDeclaration) {
				logger.error("@GeneratedSerializerMap can only be applied to a class/interface.", symbol)
				continue
			}

			generateMap(resolver, symbol)
		}

		return emptyList()
	}

	// Recursively collects every class/object declaration reachable from all files in the compilation,
	// including ones nested in other declarations (companions, other classes, etc.).
	private fun collectClasses(declarations: Sequence<KSDeclaration>): Sequence<KSClassDeclaration> =
		declarations.flatMap { declaration ->
			if (declaration is KSClassDeclaration) {
				sequenceOf(declaration) + collectClasses(declaration.declarations.asSequence())
			} else {
				emptySequence()
			}
		}

	private fun allClassDeclarations(resolver: Resolver): Sequence<KSClassDeclaration> =
		collectClasses(resolver.getAllFiles().asSequence().flatMap { it.declarations.asSequence() })

	private fun generateMap(resolver: Resolver, base: KSClassDeclaration) {
		val baseQualifiedName = base.qualifiedName?.asString()
			?: return logger.error("Base type has no qualified name.", base)

		val subclasses = allClassDeclarations(resolver)
			.filter { it.classKind == ClassKind.CLASS || it.classKind == ClassKind.OBJECT }
			.filter { Modifier.ABSTRACT !in it.modifiers && Modifier.SEALED !in it.modifiers }
			.filter { it.qualifiedName?.asString() != baseQualifiedName }
			.filter { declaration ->
				declaration.getAllSuperTypes().any { it.declaration.qualifiedName?.asString() == baseQualifiedName }
			}
			.distinctBy { it.qualifiedName?.asString() }
			.sortedBy { it.qualifiedName?.asString() }
			.toList()

		if (subclasses.isEmpty()) {
			logger.error("No concrete subtypes of '${base.simpleName.asString()}' found.", base)
			return
		}

		val simpleName = base.simpleName.asString()
		val packageName = base.packageName.asString()
		val propertyName = simpleName.replaceFirstChar { it.lowercase() } + "Serializers"

		val source = buildString {
			appendLine("// GENERATED by kore-ksp. Do not edit.")
			if (packageName.isNotEmpty()) {
				appendLine("package $packageName")
				appendLine()
			}
			appendLine("internal val $propertyName: Map<kotlin.reflect.KClass<out $simpleName>, kotlinx.serialization.KSerializer<out $simpleName>> = mapOf(")
			subclasses.forEach { subclass ->
				val fqName = subclass.qualifiedName!!.asString()
				appendLine("\t$fqName::class to $fqName.serializer(),")
			}
			appendLine(")")
		}

		val dependencySources = (listOf(base.containingFile) + subclasses.map { it.containingFile })
			.filterNotNull()
			.distinct()
			.toTypedArray()

		val file = codeGenerator.createNewFile(
			Dependencies(false, *dependencySources),
			packageName,
			"${simpleName}SerializerMap",
			"kt",
		)

		OutputStreamWriter(file).use { it.write(source) }
	}
}
