package io.github.ayfri.kore.bindings

import io.github.ayfri.kore.generated.DATAPACK_FOLDER_TO_ARGUMENT as GENERATED_DATAPACK_FOLDER_TO_ARGUMENT

/**
 * Live registry override, populated from Minecraft's generated data on platforms that can
 * safely reach the network and a local cache (JVM). Left `null` on platforms (e.g. JS/browser)
 * where the compiled-in, per-Minecraft-version [GENERATED_DATAPACK_FOLDER_TO_ARGUMENT] is used
 * instead - it's regenerated by `:generation:run` alongside every other Kore registry, so it
 * never needs a hand-maintained duplicate list here.
 */
internal var liveRegistryMapping: Map<String, String>? = null

// Mapping from datapack folder names to corresponding Kore Argument types
internal val DATAPACK_FOLDER_TO_ARGUMENT: Map<String, String>
	get() = liveRegistryMapping ?: GENERATED_DATAPACK_FOLDER_TO_ARGUMENT

/**
 * Checks if a datapack folder type has a corresponding Kore Argument interface.
 * This prevents generating invalid code for unsupported resource types.
 */
fun isValidResourceType(resourceType: String) = resourceType in DATAPACK_FOLDER_TO_ARGUMENT
