package io.github.ayfri.kore.pack

import io.github.ayfri.kore.arguments.chatcomponents.textComponent
import io.github.ayfri.kore.assertions.assertsIsJson
import io.github.ayfri.kore.generated.DataPacks
import io.github.ayfri.kore.utils.pretty
import io.github.ayfri.kore.utils.testDataPack

fun packMCMetaTests() {
	testEmptyDatapackMCMeta()
	testPackMCMetaMinMaxFormat()
	testPackMCMetaNoExtraFields()
	testPackMCMetaWithFeatures()
	testPackMCMetaWithFilter()
	testPackMCMetaWithOverlays()
}

private fun testEmptyDatapackMCMeta() = testDataPack("empty_pack") {
	pretty()
}.dp.generatePackMCMetaFile() assertsIsJson """
	{
		"pack": {
			"description": "Generated by Kore",
			"min_format": [
				94,
				0
			],
			"max_format": [
				94,
				0
			],
			"pack_format": [
				94,
				0
			]
		}
	}
""".trimIndent()

private fun testPackMCMetaMinMaxFormat() = testDataPack("minmax_pack") {
	pretty()
	pack {
		description = textComponent("My datapack")
		minFormat(90)
		maxFormat(94, 0)
	}
}.dp.generatePackMCMetaFile() assertsIsJson """
	{
		"pack": {
			"description": "My datapack",
			"min_format": 90,
			"max_format": [
				94,
				0
			],
			"pack_format": [
				94,
				0
			]
		}
	}
""".trimIndent()

@Suppress("DEPRECATION")
private fun testPackMCMetaNoExtraFields() = testDataPack("no_extra_pack") {
	pretty()
	pack {
		description = textComponent("Clean pack")
		minFormat(94, 0)
		maxFormat(94, 0)
		packFormat = null
	}
}.dp.generatePackMCMetaFile() assertsIsJson """
	{
		"pack": {
			"description": "Clean pack",
			"min_format": [
				94,
				0
			],
			"max_format": [
				94,
				0
			]
		}
	}
""".trimIndent()

@Suppress("DEPRECATION")
private fun testPackMCMetaWithFeatures() = testDataPack("features_pack") {
	pretty()
	pack {
		description = textComponent("Pack with features")
		minFormat(94, 0)
		maxFormat(94, 0)
		packFormat = null
	}
	features(DataPacks.REDSTONE_EXPERIMENTS)
}.dp.generatePackMCMetaFile() assertsIsJson """
	{
		"pack": {
			"description": "Pack with features",
			"min_format": [
				94,
				0
			],
			"max_format": [
				94,
				0
			]
		},
		"features": {
			"enabled": [
				"redstone_experiments"
			]
		}
	}
""".trimIndent()

@Suppress("DEPRECATION")
private fun testPackMCMetaWithFilter() = testDataPack("filter_pack") {
	pretty()
	pack {
		description = textComponent("Pack with filter")
		minFormat(94, 0)
		maxFormat(94, 0)
		packFormat = null
	}
	filter {
		block(path = "stone*")
	}
}.dp.generatePackMCMetaFile() assertsIsJson """
	{
		"pack": {
			"description": "Pack with filter",
			"min_format": [
				94,
				0
			],
			"max_format": [
				94,
				0
			]
		},
		"filter": {
			"block": [
				{
					"path": "stone*"
				}
			]
		}
	}
""".trimIndent()

@Suppress("DEPRECATION")
private fun testPackMCMetaWithOverlays() = testDataPack("overlays_pack") {
	pretty()
	pack {
		description = textComponent("Pack with overlays")
		minFormat(94, 0)
		maxFormat(94, 0)
		packFormat = null
	}
	overlays {
		entry("compat_overlay") {
			minFormat(82)
			maxFormat(93)
		}
	}
}.dp.generatePackMCMetaFile() assertsIsJson """
	{
		"pack": {
			"description": "Pack with overlays",
			"min_format": [
				94,
				0
			],
			"max_format": [
				94,
				0
			]
		},
		"overlays": {
			"entries": [
				{
					"directory": "compat_overlay",
					"min_format": 82,
					"max_format": 93
				}
			]
		}
	}
""".trimIndent()
