package io.github.ayfri.kore.features.worldgen.configuredcarver

import io.github.ayfri.kore.arguments.types.resources.BlockArgument
import io.github.ayfri.kore.data.block.BlockState
import io.github.ayfri.kore.data.block.BlockStateBuilder
import io.github.ayfri.kore.data.block.blockState
import kotlinx.serialization.Serializable

/**
 * Replaces the blocks a carver places, so the carved volume can be seen without exploring it.
 *
 * Every state defaults to the acacia button's default state when left unset.
 *
 * Docs: https://kore.ayfri.com/docs/data-driven/worldgen/carvers
 * Minecraft Wiki: https://minecraft.wiki/w/Carver_definition
 *
 * @property debugMode Whether the carver replaces blocks with the states below.
 * @property airState Replaces carved air.
 * @property waterState Replaces water, then waterlogs the block.
 * @property lavaState Replaces lava.
 * @property barrierState Replaces the barriers generated by aquifers.
 */
@Serializable
data class DebugSettings(
	var debugMode: Boolean? = null,
	var airState: BlockState? = null,
	var waterState: BlockState? = null,
	var lavaState: BlockState? = null,
	var barrierState: BlockState? = null,
)

/** Sets [DebugSettings.airState] to [block], with its properties configured in [init]. */
fun DebugSettings.airState(block: BlockArgument, init: BlockStateBuilder.() -> Unit = {}) {
	airState = blockState(block, init)
}

/** Sets [DebugSettings.barrierState] to [block], with its properties configured in [init]. */
fun DebugSettings.barrierState(block: BlockArgument, init: BlockStateBuilder.() -> Unit = {}) {
	barrierState = blockState(block, init)
}

/** Sets [DebugSettings.lavaState] to [block], with its properties configured in [init]. */
fun DebugSettings.lavaState(block: BlockArgument, init: BlockStateBuilder.() -> Unit = {}) {
	lavaState = blockState(block, init)
}

/** Sets [DebugSettings.waterState] to [block], with its properties configured in [init]. */
fun DebugSettings.waterState(block: BlockArgument, init: BlockStateBuilder.() -> Unit = {}) {
	waterState = blockState(block, init)
}
