package io.github.ayfri.kore

data object OopConstants {
    var advancementPrefix = "kore_oop"
    var namespace = "kore"

    var blockUseEvent = "on_block_use"
	var bredAnimalsEvent = "on_bred_animals"
	var brewedPotionEvent = "on_brewed_potion"
    var changeDimensionEvent = "on_change_dimension"
    var consumeItemEvent = "on_consume_item"
    var cooldownReadyHandlersTag = "cooldown_ready_handlers"
    var dayStartEvent = "on_day_start"
    var deathEvent = "on_death"
    var deathDispatcherFunction = "kore_oop_death_dispatcher"
    var deathHandlersTag = "on_death_handlers"
    var deathTriggerKey = "kore_oop_death"
    var effectsChangedEvent = "on_effects_changed"
    var enchantItemEvent = "on_enchant_item"
    var entityHurtPlayerEvent = "on_entity_hurt_player"
    var fallFromHeightEvent = "on_fall_from_height"
	var filledBucketEvent = "on_filled_bucket"
	var fishingRodHookedEvent = "on_fishing_rod_hooked"
    var hurtEntityEvent = "on_hurt_entity"
	var interactWithEntityEvent = "on_interact_with_entity"
    var intervalEvent = "on_interval"
    var inventoryChangeEvent = "on_inventory_change"
    var itemUsedOnBlockEvent = "on_item_used_on_block"
    var killEvent = "on_kill"
	var killedByArrowEvent = "on_killed_by_arrow"
    var lootTablePrefix = "kore_oop"
    var nightStartEvent = "on_night_start"
    var placeBlockEvent = "on_place_block"
    var rainStartEvent = "on_rain_start"
    var rainStopEvent = "on_rain_stop"
    var recipeCraftedEvent = "on_recipe_crafted"
    var rightClickEvent = "on_right_click"
	var shotCrossbowEvent = "on_shot_crossbow"
    var sleptInBedEvent = "on_slept_in_bed"
    var startRidingEvent = "on_start_riding"
    var stateHolder = "#game_state"
    var stateInitFunction = "kore_state_init"
    var stateObjective = "kore_state"
    var stateWhenHandlersTag = "state_when_handlers"
    var tameAnimalEvent = "on_tame_animal"
    var targetHitEvent = "on_target_hit"
    var thunderStartEvent = "on_thunder_start"
    var thunderStopEvent = "on_thunder_stop"
	var tickEvent = "on_tick"
    var timeOfDayEvent = "on_time_of_day"
    var timerCompleteHandlersTag = "timer_complete_handlers"
	var usedEnderEyeEvent = "on_used_ender_eye"
	var usedTotemEvent = "on_used_totem"
    var worldLoadEvent = "on_world_load"
    var worldStateInitFunction = "kore_world_init"
    var worldStateObjective = "kore_world"
    var worldTickEvent = "on_world_tick"

    fun advancementName(event: String) = "$advancementPrefix/$event"
    fun advancementNameForItem(event: String, itemName: String) = "$advancementPrefix/${event}_$itemName"
    fun cooldownInitFunctionName(name: String) = "cooldown_${name}_init"
    fun cooldownReadyHandlerName(name: String, hashCode: Int) = "cooldown_${name}_ready_$hashCode"
    fun cooldownTickFunctionName(name: String) = "cooldown_${name}_tick"
    fun deathTriggerLootTable(entityTypeName: String) = "$lootTablePrefix/death_trigger_$entityTypeName"
    fun dispatchFunctionName(event: String) = "dispatch_$event"
    fun dispatchFunctionNameForItem(event: String, itemName: String) = "dispatch_${event}_$itemName"
    fun eventHandlerName(event: String, hashCode: Int) = "${event}_handler_$hashCode"
    fun eventHandlerNameForItem(event: String, itemName: String, hashCode: Int) =
        "${event}_${itemName}_handler_$hashCode"

    fun eventTagName(event: String) = event
    fun eventTagNameForItem(event: String, itemName: String) = "${event}_$itemName"
    fun spawnerSpawnFunctionName(name: String) = "spawner_${name}_spawn"
    fun stateHandlerName(stateName: String, hashCode: Int) = "state_${stateName}_handler_$hashCode"
    fun timerCompleteFunctionName(name: String, hashCode: Int) = "timer_${name}_complete_$hashCode"
    fun timerInitFunctionName(name: String) = "timer_${name}_init"
    fun timerTickFunctionName(name: String) = "timer_${name}_tick"
    fun worldEventTag(event: String, dimensionId: String?) =
        if (dimensionId == null) event else "${event}_${dimensionId.replace(Regex("[^a-z0-9_]"), "_")}"

    fun worldStateScore(tagName: String, suffix: String) = "#$tagName.$suffix"
}
