package io.github.ayfri.kore

data object OopConstants {
    var advancementPrefix = "kore_oop"
    var namespace = "kore"

    var blockUseEvent = "on_block_use"
    var changeDimensionEvent = "on_change_dimension"
    var consumeItemEvent = "on_consume_item"
    var cooldownReadyHandlersTag = "cooldown_ready_handlers"
    var deathEvent = "on_death"
    var deathDispatcherFunction = "kore_oop_death_dispatcher"
    var deathHandlersTag = "on_death_handlers"
    var deathTriggerKey = "kore_oop_death"
    var effectsChangedEvent = "on_effects_changed"
    var enchantItemEvent = "on_enchant_item"
    var entityHurtPlayerEvent = "on_entity_hurt_player"
    var fallFromHeightEvent = "on_fall_from_height"
    var hurtEntityEvent = "on_hurt_entity"
    var inventoryChangeEvent = "on_inventory_change"
    var itemUsedOnBlockEvent = "on_item_used_on_block"
    var killEvent = "on_kill"
    var lootTablePrefix = "kore_oop"
    var placeBlockEvent = "on_place_block"
    var recipeCraftedEvent = "on_recipe_crafted"
    var rightClickEvent = "on_right_click"
    var sleptInBedEvent = "on_slept_in_bed"
    var startRidingEvent = "on_start_riding"
    var stateHolder = "#game_state"
    var stateInitFunction = "kore_state_init"
    var stateObjective = "kore_state"
    var stateWhenHandlersTag = "state_when_handlers"
    var tameAnimalEvent = "on_tame_animal"
    var targetHitEvent = "on_target_hit"
    var timerCompleteHandlersTag = "timer_complete_handlers"

    fun advancementName(event: String) = "$advancementPrefix/$event"
    fun advancementNameForItem(event: String, itemName: String) = "$advancementPrefix/${event}_$itemName"
    fun cooldownInitFunctionName(name: String) = "cooldown_${name}_init"
    fun cooldownReadyHandlerName(name: String, hashCode: Int) = "cooldown_${name}_ready_$hashCode"
    fun cooldownTickFunctionName(name: String) = "cooldown_${name}_tick"
    fun deathTriggerLootTable(entityTypeName: String) = "$lootTablePrefix/death_trigger_$entityTypeName"
    fun dispatchFunctionName(event: String) = "dispatch_$event"
    fun dispatchFunctionNameForItem(event: String, itemName: String) = "dispatch_${event}_$itemName"
    fun eventHandlerName(event: String, hashCode: Int) = "${event}_handler_$hashCode"
    fun eventHandlerNameForItem(event: String, itemName: String, hashCode: Int) =
        "${event}_${itemName}_handler_$hashCode"

    fun eventTagName(event: String) = event
    fun eventTagNameForItem(event: String, itemName: String) = "${event}_$itemName"
    fun spawnerSpawnFunctionName(name: String) = "spawner_${name}_spawn"
    fun stateHandlerName(stateName: String, hashCode: Int) = "state_${stateName}_handler_$hashCode"
    fun timerCompleteFunctionName(name: String, hashCode: Int) = "timer_${name}_complete_$hashCode"
    fun timerInitFunctionName(name: String) = "timer_${name}_init"
    fun timerTickFunctionName(name: String) = "timer_${name}_tick"
}
