package io.github.ayfri.kore.website.playground

import io.github.ayfri.kore.exportAsStrings
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import java.io.File

private const val WEBSITE_PACKAGE = "io.github.ayfri.kore.website.components.playground"

/**
 * Writes what the website needs from the examples, given the example sources folder then the output folder:
 * - `kotlin/`: the example list with each snippet as the editor shows it, its package line dropped;
 * - `resources/public/playground-examples/<slug>.json`: the files the snippet generates, in the order the page lists them.
 *
 * Not under `public/playground/`: a `playground/` folder next to the exported `playground.html` can make a static host
 * redirect the page route to a folder listing.
 */
fun main(args: Array<String>) {
	val (sources, output) = args.map(::File)
	output.deleteRecursively()

	val packs = File(output, "resources/public/playground-examples").apply { mkdirs() }
	val snippets = playgroundExamples.associateWith { example ->
		val source = File(sources, example.fileName).readText().replace("\r\n", "\n")
		val packageLine = "package ${example.packageName}"
		check(source.startsWith("$packageLine\n")) { "${example.fileName} must start with '$packageLine'." }

		val files = example.build().exportAsStrings().entries.sortedWith(compareBy({ it.key != "pack.mcmeta" }, { it.key }))
		File(packs, "${example.slug}.json").writeText(JsonObject(files.associate { it.key to JsonPrimitive(it.value) }).toString())

		source.removePrefix(packageLine).trim()
	}

	val list = buildString {
		appendLine("// Generated by :playground-examples:generatePlaygroundExamples, edit website/playground-examples instead.")
		appendLine("package $WEBSITE_PACKAGE")
		appendLine()
		appendLine("val playgroundExamples = listOf(")
		snippets.forEach { (example, code) ->
			appendLine("\tPlaygroundExample(")
			appendLine("\t\tslug = ${example.slug.literal()},")
			appendLine("\t\ttitle = ${example.title.literal()},")
			appendLine("\t\tdescription = ${example.description.literal()},")
			appendLine("\t\tcategory = ${example.category.label.literal()},")
			appendLine("\t\tcode = ${code.literal()},")
			appendLine("\t),")
		}
		appendLine(")")
	}

	File(output, "kotlin/${WEBSITE_PACKAGE.replace('.', '/')}/PlaygroundExampleList.kt").apply { parentFile.mkdirs() }.writeText(list)
	println("Generated ${snippets.size} playground examples into $output")
}

private fun String.literal() = buildString {
	append('"')
	this@literal.forEach { char ->
		when (char) {
			'\\' -> append("\\\\")
			'"' -> append("\\\"")
			'$' -> append("\\$")
			'\n' -> append("\\n")
			'\t' -> append("\\t")
			else -> append(char)
		}
	}
	append('"')
}
