package io.github.ayfri.kore.website.components.playground

import kotlinx.browser.window
import kotlinx.coroutines.await

/**
 * A starter snippet of the playground.
 *
 * The list itself, `playgroundExamples`, is generated by `:playground-examples` from real Kotlin files that compile
 * and run against Kore on every build, which is also where each example's generated pack comes from.
 */
data class PlaygroundExample(
	val slug: String,
	val title: String,
	val description: String,
	val category: String,
	val code: String,
)

/** Examples grouped for the picker, in declaration order so a category keeps the order it was written in. */
val playgroundExamplesByCategory = playgroundExamples.groupBy { it.category }

/** Reverse index used to tell whether the current buffer is still an untouched example, checked on every keystroke. */
val playgroundExamplesByCode = playgroundExamples.associateBy { it.code }

val defaultExample = playgroundExamples.first()

/** The example a `/playground#example=<slug>` link opens, which is how the rest of the site points at one. */
fun linkedExample() = window.location.hash.removePrefix("#example=").let { slug -> playgroundExamples.firstOrNull { it.slug == slug } }

/**
 * The pack this example generates, computed on the JVM at build time: one small static fetch instead of a compile, so
 * most visitors, who run an example before editing anything, never wait on the backend at all.
 */
suspend fun PlaygroundExample.precomputedFiles(): List<GeneratedFile>? = runCatching {
	val response = window.fetch("/playground-examples/$slug.json").await()
	if (!response.ok) return null

	val files = response.json().await().asDynamic()
	js("Object.keys")(files).unsafeCast<Array<String>>().map { GeneratedFile(it, files[it] as String) }
}.getOrNull()
